[DB]
HOST = "localhost"
USER = "postgres"
PASSWORD = "postgres"
DATABASE = "vkinder"

[ACCESS]
USER_TOKEN = "vk1.a._lHZbj3h0lXUPMMJfR9o4aIzzYh75lcZVxPc45VfD-TfOxhtefV4iSVU6DTAvAqB5NzunRAfcj05J8yzPZ9RzVQAwwhtWgOZCExxl21RcGd3aSTSHor79mF-csMQ8AojAHqEqMTrJeh429qRSt61GFu_zbySjxw-FUsHknF8xzftPHDSqRmE15cEcfDkjIXol_xAQXoy-aAML1t4j3-smQ"
GROUP_TOKEN = "vk1.a.4zo2EqIRQcSDKSImWDzTT6vQd0251z4PJ4fXidv1wNtYlNisMyzwlzVk-lZ49OM8ofxXd5L3TkqrW4rh5WtZ7RvSGxPDWJem4fU2jUQbn0RZ0xsP2GN2hBKNeLu_HQTYIJeeZCyQcN-QbDMdHDvV_BsgwgHM7W8Km1WJV153KkEH7yKZGfCCxoF4Kal8ekOG5oFj7NOLx6fztUw1Fk4nCw"
